name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name:  Deploy to Server
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/your-repo

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            npm install

            echo "Build app"
            npm run build

            echo "🔄 Restart app"
            pm2 restart all
          EOF
